language: rust
rust:
  - stable
  - beta
  - nightly
dist: xerus
script:
  - lsb_release -a
  - cargo test
  - cargo doc --no-deps
  - cargo run --example rainbow
  - cargo run --example thread
  - cargo run --example threadpool
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
    on_failure: never
    on_pull_requests: true
